# .scrutinizer.yml
build:
    nodes:
        tests: true
        analysis:
            tests:
                override:
                    -
                        command: pylint-run
                    - py-scrutinizer-run

checks:
    python: {  }
